### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by alrra** [alrra/travis-scripts#20]
- [x] Improve overall documentation
- [x] Improve usage related documentation
- [x] Add note about the [Travis CLI issue on Windows](https://github.com/travis-ci/travis-ci/issues/4746)  - done in https://github.com/alrra/travis-scripts/commit/9a68a74f584888cb83a9d7ab7f79a5264d126702
- [x] Make steps easier to follow (less jumping back and forth) - done in https://github.com/alrra/travis-scripts/commit/f3ec5d2634a02736dedb86ea6340a31b79e95f13
- [x] Other (which?)

**Comment by Waydrow** [comment]
I don't know why it isn't work on Windows, just the same problem.
Maybe you can try it on Ubuntu, I made it.
Every step is same as on Windows

**Comment by mathiasbynens** [comment]
Ooh, I like the `← previous step | table of contents | next step →` links at the bottom of the docs. Nice touch!

**Comment by alrra** [comment]
> I like the ← previous step | table of contents | next step → links at the bottom of the docs. 

Also, the [access token related documentation](https://github.com/alrra/travis-scripts/blob/master/doc/github-access-token.md) is not included in that flow as that method is not recommended. :bowtie:

**Comment by mathiasbynens** [comment]
IMHO that part of the docs should be removed. It’s bad practice, not recommended, and you don’t wanna waste timing maintaining it.

**Comment by alrra** [comment]
- [ ] [Add note about using the master branch's `/docs` directory for publishing](https://github.com/blog/2228-simpler-github-pages-publishing)
