### ISSUE TITLE
Unable to deploy to master

### ISSUE THREAD

**Issue by demoneaux** [alrra/travis-scripts#22]
Due to [this line](https://github.com/alrra/travis-scripts/blob/6f029b229b3b51678399061f771555e31423847c/bin/update-branch.sh#L32), the `master` branch cannot be deployed to, as `master` is the default branch and cannot be created again. Perhaps a check could be added for the `master` branch?

**Comment by alrra** [comment]
@demoneaux Nice catch, and thanks for opening this issue! :purple_heart: 

--

(Never thought someone would use the `master` branch as the distribution branch)
