### ISSUE TITLE
set-up-ssh: Consider using `--iv` instead of `-iv`, etc.

### ISSUE THREAD

**Issue by mathiasbynens** [alrra/travis-scripts#23]
Please keep in mind that this is a **really minor** “issue”.

The current API looks like this:

```sh
$(npm bin)/set-up-ssh -k "$encrypted_ca2180397773_key" \
  -iv "$encrypted_ca2180397773_iv" \
  --path-encrypted-key ".travis/github_deploy_key.enc"
```

1. Why `-iv` and not `--iv`? Generally, single-char options use `-` and multi-char options use `--` in CLIs.
2. Why is there no long-form `--` alternative for `-k`?

**Comment by alrra** [comment]
> 1. Why -iv and not --iv? 

@mathiasbynens Because I wanted to match [OpenSSL's API](https://www.openssl.org/docs/manmaster/apps/enc.html):

> -iv IV
>
>    the actual IV to use: this must be represented as a string comprised only of hex digits. When only the key is specified using the -K option, the IV must explicitly be defined. When a password is being specified using one of the other options, the IV is generated from this password.

> Generally, single-char options use `-` and multi-char options use `--` in CLIs.

In generally, yes. 

I gave this some thought, and I agree, this project will probably be better off following that convention. 

> 2. Why is there no long-form -- alternative for -k?

`--key`?

**Comment by mathiasbynens** [comment]
Just because `openssl`’s API is weird doesn’t mean `travis-scripts` has to be weird as well :) :+1: to something like `--iv/-i` and `--key/-k`.
