### ISSUE TITLE
Update `travis` instructions

### ISSUE THREAD

**Issue by mathiasbynens** [alrra/travis-scripts#33]
After running `gem install travis`, you need to run another step if you use `travis-ci.com` instead of `travis-ci.org` (which is being deprecated). The step is:

```sh
travis endpoint --pro --set-default
```

Background (no need to mention this in the docs): this updates the local config at `~/.travis/config.yml` and ensures the `travis` CLI is uploading the environment secrets to the `.com` domain.

**Comment by alrra** [comment]
> which is being deprecated

https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

---

> After running gem install travis, you need to run another step if you use travis-ci.com instead of travis-ci.org (which is being deprecated). The step is:...

@mathiasbynens If the above is still true, do you want to open a PR? Thanks!

**Comment by mathiasbynens** [comment]
For some reason, the above command stopped working for me. I now have to explicitly use the `--com` flag, e.g. `travis encrypt $file` --> `travis encrypt --com $file`.
