### ISSUE TITLE
Update branch without overwriting?

### ISSUE THREAD

**Issue by ljharb** [alrra/travis-scripts#34]
We use this to update the gh-pages branch, but every time, it uses `git init` and starts a fresh branch. Is there any way it could keep the history? That way, I could use a build command that builds - for example - each SHA separately, and keep all of them intact for historical perusal.

**Comment by alrra** [comment]
> it uses git init and starts a fresh branch.

If I remember correctly that was done as a simple way to avoid conflicts.

> Update branch without overwriting?

@ljharb I won't have time to look into this in the next few weeks, but it sounds good to me, and I'm fine with this change!
